name: Test Simple Sync
on:
  issues:
    types: [opened]

jobs:
  sync-issue:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Simple sync without assignee mapping
      uses: jessaggie/github-actions-issue-to-work-item@master
      env:
        ado_token: "${{ secrets.AZDO_WORK_ITEM_TOKEN }}"
        github_token: "${{ secrets.GH_REPO_TOKEN }}"
        ado_organization: "Myownpersonalorganizationtest"
        ado_project: "myownpersonaltest"
        ado_area_path: "myownpersonaltest\\Sprint 1"
        ado_wit: "Product Backlog Item"
        ado_new_state: "New"
        ado_active_state: "Active"
        ado_close_state: "Closed"
        ado_bypassrules: true
        log_level: 300
